### ISSUE TITLE
Details on the process

### ISSUE THREAD

**Issue by SHASANKsp** [SHASANKsp/DDCM#1] opened 2021-01-21 17:23 UTC

**Comment by Sohambiswas8** [comment] 2021-01-23 15:53
Details on the process: ### 

Aim & Objectives: 
**1**. Creating a database comprising disease-causing mutations in genomic level, corresponding mRNA variants, related protein isoform as a product and its clinical significance. 

**Overall Process plan:** 
We know that a mutation can be of several types and also it is random. But if a mutation in the gene level causes a change in the corresponding protein (as a change in amino acid residue due to change in triplet codon), then following post-translational modification the protein may function differently or lost its function as compared to its wild type. Therefore, our idea is to create a database where we will be showing the mutation location in the chromosome (as compared to the human genome mapping), the change in nucleotide from the original to the mutated one, the corresponding mRNA variants due to the mutation [Note: Even one gene can form multiple mRNA variants due to the phenomenon called Exon Skipping. Hence, it will be our target to find the possible mRNA variants from the given genetic mutation. This can be done by using an open web software called 'Mutalyzer'. 
    There is a particular nomenclature called "Human Genome Variation Society (HGVS) Nomenclature" that is used to indicate a particular mutation in a chromosome, gene (DNA), mRNA and protein isoform level. Hence our target will be to find all the corresponding variants caused by the mutation and to list them in a table-like manner as we create the database. 
    The last part is about annotating specific variant features that have been already listed. This would give an overview of the clinical interpretation and significance of the listed mutation (variant). In order to do this, it is needed to be acquainted with the guidelines **ACMG (American College of Medical Genetics & Genomics)** and **AMP (Association of Molecular Pathology)**. According to these guidelines for a specific type of variants, there are specific attributes which indicate if the concerned variant is benign or severe of a certain degree.  Therefore it is necessary to learn how to annotate the attributes as these will be included in the database. 

[**Note:** 
1. Literature search is essential for finding a specific disease-related variant and its attributes. To learn how to do this the attached files can be followed as tutorials. 
2. In the database, it will be a good idea to put the link for peer-reviewed journals i.e. literature as a reference where the variant and related clinical significance have been discussed. 
3. The reference human genome for variant searching will be used as mentioned in literature. (e.g. hg19 or hg38 etc. as an example) ]

**Comment by Sohambiswas8** [comment] 2021-01-23 16:12
[GVACI_Session 1_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860492)

**Closed by Sohambiswas8** 2021-01-23 16:12 UTC
Labels: documentation

**Comment by Sohambiswas8** [comment] 2021-01-23 16:28
The tutorials to be used: 
[GVACI_Session 1_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860496/Introduction to Genetics & Genomics.pdf)
[GVACI_Session 2_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860497/Next Generation sequencing & Population Genomics.pdf)
[GVACI_Session 3_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860510/Variant File Format & HGVS Nomenclature.pdf)
[GVACI_Session4_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860511/Interchanging Variant Nomenclature & Syntax Checking.pdf)
[GVACI_Session 5_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860522/Variants in Literature -How to go about curating variants and understanding them.pdf)
[GVACI_Session 6_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860524/Annotating variant features using online resources.pdf
[GVACI_Session 8_notes and assignments.pdf](https://github.com/SHASANKsp/DDCM/files/5860530/Literature attributes in the ACMG & AMP Guidelines for Interpretation of Sequence Variants.pdf)
[GVACI_Session 7_notes and assignment.pdf](https://github.com/SHASANKsp/DDCM/files/5860531/Introduction to ACMG & AMP guidelines for interpretation of sequence variants.pdf)
)
